# 1.Print 'Hello HCIA'.

In [36]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [37]:
a=1
b=2
print(a+b)

3


# 3.Define a list and replicate in three different ways.

In [38]:
a=['1','2','3','4']
print([a]*5)
for i in range(5):
    print(a)
from itertools import repeat
list(repeat(a, 5))

[['1', '2', '3', '4'], ['1', '2', '3', '4'], ['1', '2', '3', '4'], ['1', '2', '3', '4'], ['1', '2', '3', '4']]
['1', '2', '3', '4']
['1', '2', '3', '4']
['1', '2', '3', '4']
['1', '2', '3', '4']
['1', '2', '3', '4']


[['1', '2', '3', '4'],
 ['1', '2', '3', '4'],
 ['1', '2', '3', '4'],
 ['1', '2', '3', '4'],
 ['1', '2', '3', '4']]

# 4.Define two lists and merge them together.

In [26]:
a=['1','2','3']
b=['4','5']
print(a+b)

['1', '2', '3', '4', '5']


# 5. Get the last element of the list and print it.

In [27]:
a=['1','2','3']
print(a[2])

3


# 6.Define a tuple that contains only one element.

In [28]:
c=(1)
print(c)

1


# 7.Define a three-line long string.

In [29]:
s = ("three-line"
      " long "
      "string"
     )
print(s)

three-line long string


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [30]:
c=(1,2,3)
for i in range(3):
    print(c[i])

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [31]:
def Mul(x,y):
    return x*y

print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [32]:
import numpy as np
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [33]:
import numpy as np
a=np.zeros((4,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [34]:
import numpy 
a=numpy.arange(15,).reshape(3,5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [35]:
import numpy
a=numpy.arange(1,7).reshape(2,3)
print('a= ',a)
b=numpy.full((3,2),3)
print('b= ', b)
print('a*b= ',numpy.dot(a, b))

a=  [[1 2 3]
 [4 5 6]]
b=  [[3 3]
 [3 3]
 [3 3]]
a*b=  [[18 18]
 [45 45]]
